version: '3'
services:
  freshfooddb:
    image: 'mysql:8.0.26'
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: linh
      MYSQL_PASSWORD: linh
    volumes:
      - /home/sql-file:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    healthcheck:
      test: "exit 0"
  freshfoodbackend:
    image: 'nhlinh2207/freshfoodbackend:1'
    container_name: freshfoodbackend_container
    ports:
    - '8080:8080'
    environment:
      - DB_HOST=freshfooddb
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      freshfooddb:
        condition: service_healthy
  freshfoodclient:
    image: 'nhlinh2207/freshfoodclient:1'
    container_name: freshfoodclient_container
    ports:
      - '8082:80'
    volumes:
    - /home/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VUE_APP_BASE_URL=http://freshfoodbackend:8080
      - VUE_APP_WEBSOCKET_URL=http://freshfoodbackend:8080/ws