spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/freshfoodBackend?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&useUnicode=true&characterEncoding=utf-8
    username: ${DB_USER:root}
    password: ${DB_PASS:fireice22072001}
    #    url: jdbc:mariadb://ssa-db-container:3306/csignv2?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&useUnicode=true&characterEncoding=utf-8
    #    username: linh
    #    password: linh2
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: nguyenhoailinh2207@gmail.com
    password: pwmodavxdogmwdeq
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  redis:
    host: ${REDIS_HOST:192.168.25.129}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:linhBB}
  cache:
    type: redis

jwt:
  secret: nguyenhoailinh22072001

app:
  firebase-configuration-file: key-firebase.json
